### ISSUE TITLE
并行下载报错，麻烦请帮我看一下是哪里出了问题

### ISSUE THREAD

**Issue by leodu0926** [w871203w/AsyncJableDownloader#2]
C:\Users\leodu\Desktop\AsyncJableDownloader-main\venv\Scripts\python.exe C:/Users/leodu/Desktop/AsyncJableDownloader-main/jable.py 
輸入要下載的網址：-t urls.txt
Traceback (most recent call last):
  File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 158, in <module>
    main(urls[0])
  File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 129, in main
    video = NewJableCrawler(url, limit=limit)
  File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 11, in __init__
    self.video_name = self.get_video_name()
  File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 29, in get_video_name
    return self.url.split('/')[-2]
IndexError: list index out of range

Process finished with exit code 1

**Comment by w871203w** [comment]
> C:\Users\leodu\Desktop\AsyncJableDownloader-main\venv\Scripts\python.exe C:/Users/leodu/Desktop/AsyncJableDownloader-main/jable.py 輸入要下載的網址：-t urls.txt Traceback (most recent call last): File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 158, in main(urls[0]) File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 129, in main video = NewJableCrawler(url, limit=limit) File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 11, in **init** self.video_name = self.get_video_name() File "C:\Users\leodu\Desktop\AsyncJableDownloader-main\jable.py", line 29, in get_video_name return self.url.split('/')[-2] IndexError: list index out of range
> 
> Process finished with exit code 1

是 python jable.py -t urls.txt
他是指令

**Comment by leodu0926** [comment]
非常感谢
